### ISSUE TITLE
total data loss

### ISSUE THREAD

**Issue by meaninglessidentifier** [bernhard-hofmann/Tabsets#13]
i recently created a large tabset and found shortly thereafter that all of my tabsets had disappeared.  

i suspect that the call to `chrome.storage.sync.set()` in `storeTabsets()` failed (possibly because the amount of data it was attempting to store exceeded the chrome storage quota - see https://developer.chrome.com/extensions/storage#property-sync).  

since `chrome.storage.sync.clear()` is called first and no attempt is made to verify that the call to `chrome.storage.sync.set()` actually succeeds (no callback is provided), this seems likely to have been the cause.  

regardless of how it happened, i just lost a lot of research.  

if anyone has any ideas about how i might be able to recover the data, i'd be very interested to know.  

the chrome storage api doesn't appear to provide any kind of "history" functionality, and i've poked around in several of the databases in my chromium profile directory, but have been unable to find any kind of backup.

**Comment by bernhard-hofmann** [comment]
Aw maaaan. I'm so sorry for your loss. I'll look into this and see what we can do to prevent it happening in the future, but as you say there doesn't appear to be an history/backup/recovery functionality.

I don't suppose you maybe used the export feature of Tabsets at any point? That'd be one way of recovering, but I don't think it's a feature many people use.

Finally, thank you for logging the bug and including your investigations into the cause.

**Comment by imbachb** [comment]
I love this extension for it's simplicity and ease of use. Over the time my tabsets got large too and now they get wiped whenever I open the extension which sadly renders it unusable for me. Luckily I used chrome on various PCs/Laptops so I always had a backup thanks to the sync feature, which now is its downfall.

**Comment by mikhoul** [comment]
You could save to  local storage without the sync and having an option to use Sync = Limited Storage OR Local = Unlimited Storage.

Regards :octocat:
