### ISSUE TITLE
Wrong Time

### ISSUE THREAD

**Issue by smaragdus** [bernhard-hofmann/Tabsets#19]
Hello Bernhard,

I have tested about a dozen session managers for Chromium and your [Tabsets](https://bernhard-hofmann.github.io/Tabsets/) is my current favourite- the extension is easy to use yet it provides a good set of features, excellent work, thank you very much.

During my initial tests **Tabsets** behaved as expected with a single exception- it sets wrong time for"created" parameter, for example, if I save a session at 15:18 the "created" parameter looks like this:

`{"created":"2019-06-11 12:18",`

In short- **Tabsets** sets "created" parameter 3 hours earlier than the actual creation time.

I have found a workaround to correct this quirk:

- Open **Tabsets**;
- Select a tabset;
- Run **Export this tabset** command;
- Copy tabset data;
- Run **Done** command;
- Run **Delete this tabset** command;
- Open a text editor, paste data, edit "created" parameter and copy edited data;
- Open **Tabsets** again;
- Run **Import a tabset** command;
- Paste edited data;
- Run **Import** command;

This procedure works fine but it is awkward. Where does **Tabsets** get time from, not from system time? Have you encountered this problem? Do you need some additional details?

I like **Tabsets** very much- it comes closest to my requirements for a session manager. If the extension is not abandoned I might suggest several tiny enhancements for future releases.

Regards

**Comment by bernhard-hofmann** [comment]
Hello and thank you for your detailed report. I'll have to check the code, but it could be that the date and time is UTC. Could it be that you're 3 hours ahead of GMT?

I'll look into this tomorrow. Thank you again for the detail in your issue report.

**Comment by smaragdus** [comment]
@bernhard-hofmann 

Thank you for your quick response.

My time- Eastern European Summer Time - GMT/UTC +3.

These are my Windows time and date settings:

![snipaste-2019-06-12_011024](https://user-images.githubusercontent.com/9025757/59310417-f2f74400-8cae-11e9-9388-41ebd4fde2e7.png)

I checked my clock- it was about 9 seconds behind but I suppose that this does not matter.

**Comment by bernhard-hofmann** [comment]
I've just checked the code and it does indeed create the tabset with the UTC date and time. Line 65 of https://github.com/bernhard-hofmann/Tabsets/blob/master/js/app/popup.js:

`https://github.com/bernhard-hofmann/Tabsets/blob/master/js/app/popup.js`

I believe this is good practice for storage (should be UTC/GMT) but I'll localise it when showing it in the list. The time is not important to me so I'm inclined to remove it, but people may have grown used to it or actually want to see the time.

**Comment by bernhard-hofmann** [comment]
Version 1.19 is published and pending review.

**Comment by smaragdus** [comment]
@bernhard-hofmann 

Thank you for confirming the problem and for the quick fix! I have just tested version **1.19** and the tab sets are saved with the right time.

> The time is not important to me so I'm inclined to remove it, but people may have grown used to it or actually want to see the time.

For me it is useful to see when a session was created. With **Created** parameter available **Tabsets** can also serve as a a basic journal for my research.

I may open some new issues about possible enhancements. Of course I do not expect them to be implemented soon or to be implemented at all.

Since the problem is fixed I will close the issue, thanks.
