### ISSUE TITLE
Sorting

### ISSUE THREAD

**Issue by smaragdus** [bernhard-hofmann/Tabsets#20]
I would appreciate if the user can sort the tab sets- now they are sorted according to creation time. I prefer alphabetical sorting. My suggestion- **Name** and **Created** are clickable- if the user clicks on **Name** the tab sets are sorted in alphabetical order, if the user clicks on **Created** then tab sets are sorted according to creation time. I am suggesting this implementation because **Tabsets** does not have **Options**, if it had there might be a check box **Sort in Alphabetical Order**. For me sorting in alphabetical order will be handy for easier finding the needed tab set, especially when there are too many tab sets.

**Comment by smaragdus** [comment]
I saw that there was similar issue (#15) but I had already posted this one, I am sorry for the duplicate issue.

**Comment by bernhard-hofmann** [comment]
I like the suggestions. I think it might also be nice to manually order them by dragging them in the list.

**Comment by smaragdus** [comment]
@bernhard-hofmann 

Thank you very much for implementing sorting according to **Name** and **Created**. I have just tested **Tabsets** version **1.20** and it really works as expected, excellent work. Until now I had to use a very clumsy and ugly workaround to have the tab sets in alphabetical order- export previously created tab sets, delete them and re-create them in alphabetical sequence. Version **1.20** spares me this nuisance.

> I think it might also be nice to manually order them by dragging them in the list.

Custom sorting via drag&drop will be fine too.

Best regards
