### ISSUE TITLE
Quota Exceeded

### ISSUE THREAD

**Issue by smaragdus** [bernhard-hofmann/Tabsets#24]
While using **Tabsets**  version **1.20** I got the following error message:

`QUOTA_BYTES_PER_ITEM quota exceeded`

screen:

![Tabsets 1 20 - 2019-11-03 - quota exceeded - 003](https://user-images.githubusercontent.com/9025757/68091550-d93ae100-fe89-11e9-9e1a-becf7e924189.png)

The tab set I tried to add a single tab already contained 43 tabs.

This limitation prevents me from organizing tabs thematically. I hope that with future releases this limitation would be removed (if Chromium allows that).

**Comment by smaragdus** [comment]
Ah, this seems to be a duplicate of #16.

**Comment by bernhard-hofmann** [comment]
Sorry about the delay, I get so many notifications on other projects I'm involved in this one for pushed to the bottom of the 100+ issues to read through.

Were you logged in? Did logging in resolve the issue? Maybe I could include the actual size in bytes to show why the Tabset can't be saved? Or do you have any suggestions about what it could do differently? One idea is to store the Tabsets locally only (not in the Chrome shared storage) but the Tabsets won't appear on other computers you logged into then. Would that be an acceptable option?

**Comment by smaragdus** [comment]
@bernhard-hofmann 

> Sorry about the delay, I get so many notifications on other projects I'm involved in this one for pushed to the bottom of the 100+ issues to read through.

This is no problem at all.

> Were you logged in? Did logging in resolve the issue?

I never log in. I prefer to export data locally and then, if needed, upload the files to the cloud.

> Maybe I could include the actual size in bytes to show why the Tabset can't be saved?

I clicked `Export this tabset` button, copied the data, saved it to text file and checked its size- the size is 8,157 bytes. Is this what I was supposed to do? This particular tabset contains 43 tabs. However I have other tabsets which contain more tabs yet I can add more tabs to them.

> Or do you have any suggestions about what it could do differently? One idea is to store the Tabsets locally only (not in the Chrome shared storage) but the Tabsets won't appear on other computers you logged into then. Would that be an acceptable option?

I don't know, really. I don't log in and I don't synchronize browser data in the traditional way. I use [Cent Browser](https://www.centbrowser.com/) (Chromium fork) which has a portable version and this browser, in contrast with other Chromium based browsers, seems capable of preserving all user data (including installed extensions) so one can for example copy the program folder to an external drive and run it on other machines with all user data preserved. But I suppose that other user who prefer to log in (which of course is the easier solution, it is that I just do not trust Google and Mozilla) would need data to be saved in Chrome shared storage. By the way have you ever experienced this problem? I will make an experiment- I will copy the tabset which is causing the problem, delete it and then add it anew and I will check whether the problem will persist.

**Comment by smaragdus** [comment]
I deleted the the tabset and then imported it- the error message appeared again but despite that I was able to add new tabs to this tabset. As far as I can remember before when I clicked Add button (`Add the current tab to this tabset`) the error message appeared but the tab was not added to the tabset while now the error message still shows up but the tab is added to the tabset.

**Comment by smaragdus** [comment]
If you choose to add Options to Tabsets in the future there might be an option where to store data- locally or in shared storage.
